services:
  bookstore:
    image: bookstore:latest
    networks:
      - books-net
    restart: always
    ports:
      - 80:80

    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: Qq123456
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: aredotech
      MYSQL_PASSWORD: Aredotech_1

    volumes:
      - mysql-volume:/var/lib/mysql

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      # test: ["CMD", "mysqladmin", "ping", "-h", "database", "-u", "root", "--password=Qq123456"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

    networks:
      - books-net

volumes:
  mysql-volume:

networks:
  books-net:
